POST  http://localhost:3000/students/account

###
//Todos los alumnos que son becados
GET http://localhost:3000/students/scholarshipHolder?limit=100 HTTP/1.1

###
//Todos los alumnos mayores de 21 años
GET http://localhost:3000/students/legalAge?limit=100 HTTP/1.1

###
//Todos los alumnos entre los 26 y 28 años
GET http://localhost:3000/students/rangeAge?limit=100 HTTP/1.1


